// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, ProjectsReadProjectsData, ProjectsReadProjectsResponse, ProjectsCreateProjectData, ProjectsCreateProjectResponse, ProjectsReadProjectData, ProjectsReadProjectResponse, ProjectsUpdateProjectData, ProjectsUpdateProjectResponse, ProjectsDeleteProjectData, ProjectsDeleteProjectResponse, TimeEntriesGetSummaryResponse, TimeEntriesReadTimeEntriesData, TimeEntriesReadTimeEntriesResponse, TimeEntriesCreateTimeEntryData, TimeEntriesCreateTimeEntryResponse, TimeEntriesReadTimeEntryData, TimeEntriesReadTimeEntryResponse, TimeEntriesUpdateTimeEntryData, TimeEntriesUpdateTimeEntryResponse, TimeEntriesDeleteTimeEntryData, TimeEntriesDeleteTimeEntryResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ItemsService {
    /**
     * Read Items
     * Purpose: Retrieve paginated list of items for current user
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * skip (int): input - Pagination offset
     * limit (int): input - Max items per page
     * items (ItemsPublic): output - Paginated items list with count
     *
     * Relationships:
     * Consumes: Item table, current user context
     * Produces: ItemsPublic response
     *
     * Flow:
     * 1. Check if superuser (query all) or regular user (query owned only)
     * 2. Count matching items and fetch paginated results
     * 3. Return ItemsPublic with data and count
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Purpose: Create a new item owned by the current user
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * item_in (ItemCreate): input - Item creation payload
     * item (ItemPublic): output - Created item
     *
     * Relationships:
     * Consumes: ItemCreate schema, current user context
     * Produces: Item table row, ItemPublic response
     *
     * Flow:
     * 1. Validate input and set owner_id to current user
     * 2. Persist item to database
     * 3. Return created item
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Purpose: Retrieve a single item by ID with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Item ID
     * item (ItemPublic): output - Item details
     *
     * Relationships:
     * Consumes: Item table, current user context
     * Produces: ItemPublic response
     *
     * Flow:
     * 1. Fetch item by ID, raise 404 if not found
     * 2. Verify ownership or superuser role, raise 403 if denied
     * 3. Return item
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Purpose: Update an existing item with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Item ID
     * item_in (ItemUpdate): input - Partial update payload
     * item (ItemPublic): output - Updated item
     *
     * Relationships:
     * Consumes: Item table, ItemUpdate schema, current user context
     * Produces: Updated Item table row, ItemPublic response
     *
     * Flow:
     * 1. Fetch item by ID, raise 404 if not found
     * 2. Verify ownership or superuser role, raise 403 if denied
     * 3. Apply partial update and persist
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Purpose: Delete an item with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Item ID
     * message (Message): output - Deletion confirmation
     *
     * Relationships:
     * Consumes: Item table, current user context
     * Produces: Message response
     *
     * Flow:
     * 1. Fetch item by ID, raise 404 if not found
     * 2. Verify ownership or superuser role, raise 403 if denied
     * 3. Delete item and return confirmation
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * Purpose: Authenticate user via email/password and return JWT access token
     *
     * Structure:
     * session (SessionDep): input - Database session
     * form_data (OAuth2PasswordRequestForm): input - Username (email) and password
     * token (Token): output - JWT access token
     *
     * Relationships:
     * Consumes: crud.authenticate, core.security.create_access_token
     * Produces: Token response
     *
     * Flow:
     * 1. Authenticate user via crud, raise 400 if invalid credentials
     * 2. Raise 400 if user is inactive
     * 3. Create and return JWT access token with configured expiry
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Purpose: Validate access token and return current user profile
     *
     * Structure:
     * current_user (CurrentUser): input - Authenticated user from token
     * user (UserPublic): output - Current user profile
     *
     * Relationships:
     * Consumes: CurrentUser dependency (validates token implicitly)
     * Produces: UserPublic response
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Purpose: Send password recovery email if user exists
     *
     * Structure:
     * email (str): input - User email address
     * session (SessionDep): input - Database session
     * message (Message): output - Generic confirmation message
     *
     * Relationships:
     * Consumes: crud.get_user_by_email, utils.generate_password_reset_token, utils.send_email
     * Produces: Message response, password reset email
     *
     * Flow:
     * 1. Look up user by email
     * 2. If found, generate reset token and send recovery email
     * 3. Return same message regardless of email existence (prevents enumeration)
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Purpose: Reset user password using a recovery token
     *
     * Structure:
     * session (SessionDep): input - Database session
     * body (NewPassword): input - Reset token and new password
     * message (Message): output - Success confirmation
     *
     * Relationships:
     * Consumes: utils.verify_password_reset_token, crud.get_user_by_email, crud.update_user
     * Produces: Message response, updated password hash in User table
     *
     * Flow:
     * 1. Verify reset token and extract email, raise 400 if invalid
     * 2. Look up user by email, raise 400 if not found or inactive
     * 3. Update password hash and return confirmation
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * Purpose: Preview password recovery email HTML content (superuser only)
     *
     * Structure:
     * email (str): input - Target user email
     * session (SessionDep): input - Database session
     * html (HTMLResponse): output - Rendered email HTML
     *
     * Relationships:
     * Consumes: crud.get_user_by_email, utils.generate_password_reset_token, utils.generate_reset_password_email
     * Produces: HTMLResponse with email content and subject header
     *
     * Flow:
     * 1. Look up user by email, raise 404 if not found
     * 2. Generate reset token and email content
     * 3. Return HTML response with subject in headers
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Purpose: Create user directly without email uniqueness check (local dev only)
     *
     * Structure:
     * user_in (PrivateUserCreate): input - User creation payload
     * session (SessionDep): input - Database session
     * user (UserPublic): output - Created user
     *
     * Relationships:
     * Consumes: PrivateUserCreate schema, core.security.get_password_hash
     * Produces: User table row, UserPublic response
     *
     * Flow:
     * 1. Build User model with hashed password
     * 2. Persist to database
     * 3. Return created user
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ProjectsService {
    /**
     * Read Projects
     * Purpose: Retrieve paginated list of projects for current user
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * skip (int): input - Pagination offset
     * limit (int): input - Max projects per page
     * projects (ProjectsPublic): output - Paginated projects list with count
     *
     * Flow:
     * 1. Check if superuser (query all) or regular user (query owned only)
     * 2. Count matching projects and fetch paginated results
     * 3. Return ProjectsPublic with data and count
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ProjectsPublic Successful Response
     * @throws ApiError
     */
    public static readProjects(data: ProjectsReadProjectsData = {}): CancelablePromise<ProjectsReadProjectsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/projects/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Project
     * Purpose: Create a new project owned by the current user
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * project_in (ProjectCreate): input - Project creation payload
     * project (ProjectPublic): output - Created project
     *
     * Flow:
     * 1. Validate input and set owner_id to current user
     * 2. Persist project to database
     * 3. Return created project
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ProjectPublic Successful Response
     * @throws ApiError
     */
    public static createProject(data: ProjectsCreateProjectData): CancelablePromise<ProjectsCreateProjectResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/projects/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Project
     * Purpose: Retrieve a single project by ID with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Project ID
     * project (ProjectPublic): output - Project details
     *
     * Flow:
     * 1. Fetch project by ID, raise 404 if not found
     * 2. Verify ownership or superuser role, raise 403 if denied
     * 3. Return project
     * @param data The data for the request.
     * @param data.id
     * @returns ProjectPublic Successful Response
     * @throws ApiError
     */
    public static readProject(data: ProjectsReadProjectData): CancelablePromise<ProjectsReadProjectResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/projects/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Project
     * Purpose: Update an existing project with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Project ID
     * project_in (ProjectUpdate): input - Partial update payload
     * project (ProjectPublic): output - Updated project
     *
     * Flow:
     * 1. Fetch project by ID, raise 404 if not found
     * 2. Verify ownership or superuser role, raise 403 if denied
     * 3. Apply partial update and persist
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ProjectPublic Successful Response
     * @throws ApiError
     */
    public static updateProject(data: ProjectsUpdateProjectData): CancelablePromise<ProjectsUpdateProjectResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/projects/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Project
     * Purpose: Delete a project with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Project ID
     * message (Message): output - Deletion confirmation
     *
     * Flow:
     * 1. Fetch project by ID, raise 404 if not found
     * 2. Verify ownership or superuser role, raise 403 if denied
     * 3. Delete project and return confirmation
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteProject(data: ProjectsDeleteProjectData): CancelablePromise<ProjectsDeleteProjectResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/projects/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TimeEntriesService {
    /**
     * Get Summary
     * Purpose: Aggregate total minutes and per-project breakdown for the current user
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * summary (TimeSummary): output - Total minutes and per-project list
     *
     * Relationships:
     * Consumes: TimeEntry table, Project table, current user context
     * Produces: TimeSummary response
     *
     * Flow:
     * 1. Build aggregation query: sum(duration_minutes) grouped by project_id, joined with Project for name
     * 2. Scope to owner_id unless superuser
     * 3. Compute total_minutes from aggregated rows
     * 4. Return TimeSummary with total_minutes=0 and by_project=[] when no entries exist
     *
     * Important:
     * This route MUST be registered before GET /{id} to prevent FastAPI treating "summary" as a UUID.
     * @returns TimeSummary Successful Response
     * @throws ApiError
     */
    public static getSummary(): CancelablePromise<TimeEntriesGetSummaryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/time-entries/summary'
        });
    }
    
    /**
     * Read Time Entries
     * Purpose: Retrieve paginated list of time entries for current user
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * skip (int): input - Pagination offset
     * limit (int): input - Max entries per page
     * entries (TimeEntriesPublic): output - Paginated time entries list with count
     *
     * Relationships:
     * Consumes: TimeEntry table, current user context
     * Produces: TimeEntriesPublic response
     *
     * Flow:
     * 1. Check if superuser (query all) or regular user (query owned only)
     * 2. Count matching entries and fetch paginated results
     * 3. Return TimeEntriesPublic with data and count
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns TimeEntriesPublic Successful Response
     * @throws ApiError
     */
    public static readTimeEntries(data: TimeEntriesReadTimeEntriesData = {}): CancelablePromise<TimeEntriesReadTimeEntriesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/time-entries/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Time Entry
     * Purpose: Create a new time entry owned by the current user after validating project ownership
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * entry_in (TimeEntryCreate): input - Time entry creation payload
     * entry (TimeEntryPublic): output - Created time entry
     *
     * Relationships:
     * Consumes: TimeEntryCreate schema, Project table, current user context
     * Produces: TimeEntry table row, TimeEntryPublic response
     *
     * Flow:
     * 1. Fetch project by project_id; raise 404 if not found
     * 2. Verify project ownership or superuser role; raise 403 if denied
     * 3. Create time entry with owner_id = current_user.id
     * 4. Persist and return created entry
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TimeEntryPublic Successful Response
     * @throws ApiError
     */
    public static createTimeEntry(data: TimeEntriesCreateTimeEntryData): CancelablePromise<TimeEntriesCreateTimeEntryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/time-entries/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Time Entry
     * Purpose: Retrieve a single time entry by ID with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Time entry ID
     * entry (TimeEntryPublic): output - Time entry details
     *
     * Relationships:
     * Consumes: TimeEntry table, current user context
     * Produces: TimeEntryPublic response
     *
     * Flow:
     * 1. Fetch entry by ID; raise 404 if not found
     * 2. Verify ownership or superuser role; raise 403 if denied
     * 3. Return entry
     * @param data The data for the request.
     * @param data.id
     * @returns TimeEntryPublic Successful Response
     * @throws ApiError
     */
    public static readTimeEntry(data: TimeEntriesReadTimeEntryData): CancelablePromise<TimeEntriesReadTimeEntryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/time-entries/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Time Entry
     * Purpose: Partially update an existing time entry with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Time entry ID
     * entry_in (TimeEntryUpdate): input - Partial update payload
     * entry (TimeEntryPublic): output - Updated time entry
     *
     * Relationships:
     * Consumes: TimeEntry table, TimeEntryUpdate schema, current user context
     * Produces: Updated TimeEntry table row, TimeEntryPublic response
     *
     * Flow:
     * 1. Fetch entry by ID; raise 404 if not found
     * 2. Verify ownership or superuser role; raise 403 if denied
     * 3. Apply partial update (exclude_unset=True) and persist
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns TimeEntryPublic Successful Response
     * @throws ApiError
     */
    public static updateTimeEntry(data: TimeEntriesUpdateTimeEntryData): CancelablePromise<TimeEntriesUpdateTimeEntryResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/time-entries/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Time Entry
     * Purpose: Delete a time entry with ownership check
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * id (uuid.UUID): input - Time entry ID
     * message (Message): output - Deletion confirmation
     *
     * Relationships:
     * Consumes: TimeEntry table, current user context
     * Produces: Message response
     *
     * Flow:
     * 1. Fetch entry by ID; raise 404 if not found
     * 2. Verify ownership or superuser role; raise 403 if denied
     * 3. Delete entry and return confirmation
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteTimeEntry(data: TimeEntriesDeleteTimeEntryData): CancelablePromise<TimeEntriesDeleteTimeEntryResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/time-entries/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Purpose: Retrieve paginated list of all users (superuser only)
     *
     * Structure:
     * session (SessionDep): input - Database session
     * skip (int): input - Pagination offset
     * limit (int): input - Max users per page
     * users (UsersPublic): output - Paginated users list with count
     *
     * Relationships:
     * Consumes: User table
     * Produces: UsersPublic response
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Purpose: Create a new user (superuser only), send welcome email if SMTP configured
     *
     * Structure:
     * session (SessionDep): input - Database session
     * user_in (UserCreate): input - User creation payload
     * user (UserPublic): output - Created user
     *
     * Relationships:
     * Consumes: crud.get_user_by_email, crud.create_user, utils.send_email
     * Produces: User table row, UserPublic response, welcome email
     *
     * Flow:
     * 1. Check email uniqueness, raise 400 if duplicate
     * 2. Create user via crud
     * 3. Send welcome email if SMTP enabled
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Purpose: Get current authenticated user profile
     *
     * Structure:
     * current_user (CurrentUser): input - Authenticated user
     * user (UserPublic): output - Current user profile
     *
     * Relationships:
     * Consumes: CurrentUser dependency
     * Produces: UserPublic response
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Purpose: Delete own account (superusers cannot delete themselves)
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * message (Message): output - Deletion confirmation
     *
     * Relationships:
     * Consumes: User table
     * Produces: Message response
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Purpose: Update own profile (name and email)
     *
     * Structure:
     * session (SessionDep): input - Database session
     * user_in (UserUpdateMe): input - Partial profile update
     * current_user (CurrentUser): input - Authenticated user
     * user (UserPublic): output - Updated user profile
     *
     * Relationships:
     * Consumes: crud.get_user_by_email, User table
     * Produces: Updated User table row, UserPublic response
     *
     * Flow:
     * 1. If email changing, check uniqueness (raise 409 if taken)
     * 2. Apply partial update to current user
     * 3. Persist and return updated user
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Purpose: Change own password with current password verification
     *
     * Structure:
     * session (SessionDep): input - Database session
     * body (UpdatePassword): input - Current and new passwords
     * current_user (CurrentUser): input - Authenticated user
     * message (Message): output - Success confirmation
     *
     * Relationships:
     * Consumes: core.security.verify_password, core.security.get_password_hash
     * Produces: Updated password hash in User table, Message response
     *
     * Flow:
     * 1. Verify current password, raise 400 if incorrect
     * 2. Reject if new password equals current, raise 400
     * 3. Hash new password, persist, and return confirmation
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Purpose: Public self-registration (no auth required)
     *
     * Structure:
     * session (SessionDep): input - Database session
     * user_in (UserRegister): input - Registration payload
     * user (UserPublic): output - Created user
     *
     * Relationships:
     * Consumes: crud.get_user_by_email, crud.create_user
     * Produces: User table row, UserPublic response
     *
     * Flow:
     * 1. Check email uniqueness, raise 400 if duplicate
     * 2. Convert to UserCreate and create user via crud
     * 3. Return created user
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Purpose: Get user by ID (own profile or superuser only)
     *
     * Structure:
     * user_id (uuid.UUID): input - Target user ID
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated user
     * user (UserPublic): output - User profile
     *
     * Relationships:
     * Consumes: User table, current user context
     * Produces: UserPublic response
     *
     * Flow:
     * 1. Fetch user by ID
     * 2. Return immediately if requesting own profile
     * 3. Raise 403 if not superuser, raise 404 if user not found
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Purpose: Update a user by ID (superuser only)
     *
     * Structure:
     * session (SessionDep): input - Database session
     * user_id (uuid.UUID): input - Target user ID
     * user_in (UserUpdate): input - Partial update payload
     * user (UserPublic): output - Updated user
     *
     * Relationships:
     * Consumes: crud.get_user_by_email, crud.update_user, User table
     * Produces: Updated User table row, UserPublic response
     *
     * Flow:
     * 1. Fetch user by ID, raise 404 if not found
     * 2. If email changing, check uniqueness (raise 409 if taken)
     * 3. Update user via crud and return
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Purpose: Delete a user and their items (superuser only, cannot self-delete)
     *
     * Structure:
     * session (SessionDep): input - Database session
     * current_user (CurrentUser): input - Authenticated superuser
     * user_id (uuid.UUID): input - Target user ID
     * message (Message): output - Deletion confirmation
     *
     * Relationships:
     * Consumes: User table, Item table
     * Produces: Message response
     *
     * Flow:
     * 1. Fetch user by ID, raise 404 if not found
     * 2. Raise 403 if attempting self-deletion
     * 3. Delete user's items, then delete user
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Purpose: Send test email to verify SMTP configuration (superuser only)
     *
     * Structure:
     * email_to (EmailStr): input - Recipient email address
     * message (Message): output - Success confirmation
     *
     * Relationships:
     * Consumes: utils.generate_test_email, utils.send_email
     * Produces: Message response, test email
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * Purpose: Return true if application is running
     *
     * Structure:
     * result (bool): output - Always True
     *
     * Relationships:
     * Consumes: None
     * Produces: bool response
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}