// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Purpose: Schema for item creation
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Purpose: Item response schema with owner reference
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

/**
 * Purpose: Paginated item list response
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * Purpose: Schema for item update (all fields optional)
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Purpose: Generic API message response
 */
export type Message = {
    message: string;
};

/**
 * Purpose: Schema for token-based password reset
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Purpose: Schema for private user creation (bypasses SQLModel validation)
 *
 * Structure:
 * email (str): input - User email
 * password (str): input - Plain text password
 * full_name (str): input - User display name
 * is_verified (bool): input - Verification status (default False)
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Purpose: Schema for project creation
 */
export type ProjectCreate = {
    name: string;
    description?: (string | null);
};

/**
 * Purpose: Project response schema with owner reference
 */
export type ProjectPublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

/**
 * Purpose: Paginated project list response
 */
export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

/**
 * Purpose: Per-project aggregated time summary
 */
export type ProjectSummary = {
    project_id: string;
    project_name: string;
    total_minutes: number;
};

/**
 * Purpose: Schema for project update (all fields optional)
 */
export type ProjectUpdate = {
    name?: (string | null);
    description?: (string | null);
};

/**
 * Purpose: Paginated time entry list response
 */
export type TimeEntriesPublic = {
    data: Array<TimeEntryPublic>;
    count: number;
};

/**
 * Purpose: Schema for time entry creation
 */
export type TimeEntryCreate = {
    project_id: string;
    date: string;
    duration_minutes: number;
    description?: (string | null);
};

/**
 * Purpose: TimeEntry response schema with owner reference
 */
export type TimeEntryPublic = {
    project_id: string;
    date: string;
    duration_minutes: number;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

/**
 * Purpose: Schema for time entry update (all fields optional)
 */
export type TimeEntryUpdate = {
    project_id?: (string | null);
    date?: (string | null);
    duration_minutes?: (number | null);
    description?: (string | null);
};

/**
 * Purpose: Aggregated time summary across all projects for a user
 */
export type TimeSummary = {
    total_minutes: number;
    by_project: Array<ProjectSummary>;
};

/**
 * Purpose: JWT access token response
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Purpose: Schema for authenticated password change
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Purpose: Schema for admin user creation (includes role flags from UserBase)
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Purpose: User response schema (excludes hashed_password)
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * Purpose: Schema for public self-registration (no role flags)
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Purpose: Paginated user list response
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Purpose: Schema for admin user update (all fields optional)
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Purpose: Schema for self-profile update (name and email only)
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsReadProjectData = {
    id: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsUpdateProjectData = {
    id: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    id: string;
};

export type ProjectsDeleteProjectResponse = (Message);

export type TimeEntriesGetSummaryResponse = (TimeSummary);

export type TimeEntriesReadTimeEntriesData = {
    limit?: number;
    skip?: number;
};

export type TimeEntriesReadTimeEntriesResponse = (TimeEntriesPublic);

export type TimeEntriesCreateTimeEntryData = {
    requestBody: TimeEntryCreate;
};

export type TimeEntriesCreateTimeEntryResponse = (TimeEntryPublic);

export type TimeEntriesReadTimeEntryData = {
    id: string;
};

export type TimeEntriesReadTimeEntryResponse = (TimeEntryPublic);

export type TimeEntriesUpdateTimeEntryData = {
    id: string;
    requestBody: TimeEntryUpdate;
};

export type TimeEntriesUpdateTimeEntryResponse = (TimeEntryPublic);

export type TimeEntriesDeleteTimeEntryData = {
    id: string;
};

export type TimeEntriesDeleteTimeEntryResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);


/**
 * Purpose: Schema for vacation request creation
 */
export type VacationRequestCreate = {
    start_date: string;
    end_date: string;
    reason: string;
};

/**
 * Purpose: VacationRequest response schema with owner reference
 */
export type VacationRequestPublic = {
    start_date: string;
    end_date: string;
    reason: string;
    status: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

/**
 * Purpose: Paginated vacation request list response
 */
export type VacationRequestsPublic = {
    data: Array<VacationRequestPublic>;
    count: number;
};

/**
 * Purpose: Schema for vacation request update (all fields optional)
 */
export type VacationRequestUpdate = {
    start_date?: (string | null);
    end_date?: (string | null);
    reason?: (string | null);
    status?: (string | null);
};

export type VacationRequestsReadVacationRequestsData = {
    limit?: number;
    skip?: number;
};

export type VacationRequestsReadVacationRequestsResponse = (VacationRequestsPublic);

export type VacationRequestsCreateVacationRequestData = {
    requestBody: VacationRequestCreate;
};

export type VacationRequestsCreateVacationRequestResponse = (VacationRequestPublic);

export type VacationRequestsReadVacationRequestData = {
    id: string;
};

export type VacationRequestsReadVacationRequestResponse = (VacationRequestPublic);

export type VacationRequestsUpdateVacationRequestData = {
    id: string;
    requestBody: VacationRequestUpdate;
};

export type VacationRequestsUpdateVacationRequestResponse = (VacationRequestPublic);

export type VacationRequestsDeleteVacationRequestData = {
    id: string;
};

export type VacationRequestsDeleteVacationRequestResponse = (Message);
